// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { brokeredPreviewStorage } from './previewAuthStorage';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

const LOCAL_DEMO_USERS = {
  '22418104@dut4life.ac.za': { id: 'local-admin-bhengu', name: 'Mr Bhengu', role: 'admin', password: 'group21' },
  'demo.lindiwe@dut4life.ac.za': { id: 'local-student-lindiwe', name: 'Lindiwe Mkhize', role: 'student', password: 'SkillQuestDemo1!' },
  'demo.sipho@dut4life.ac.za': { id: 'local-student-sipho', name: 'Sipho Ndlovu', role: 'student', password: 'SkillQuestDemo1!' },
  'demo.nomvula@dut4life.ac.za': { id: 'local-student-nomvula', name: 'Nomvula Dube', role: 'student', password: 'SkillQuestDemo1!' },
  'demo.thabo@dut4life.ac.za': { id: 'local-student-thabo', name: 'Thabo Zwane', role: 'student', password: 'SkillQuestDemo1!' },
  'demo.zodwa@dut4life.ac.za': { id: 'local-student-zodwa', name: 'Zodwa Mthembu', role: 'student', password: 'SkillQuestDemo1!' },
  'demo.aphiwe@dut4life.ac.za': { id: 'local-student-aphiwe', name: 'Aphiwe Dlamini', role: 'student', password: 'SkillQuestDemo1!' },
  'demo.staff@dut4life.ac.za': { id: 'local-staff-zanele', name: 'Zanele Khumalo', role: 'staff', password: 'SkillQuestDemo1!' },
  'demo.nomsa@dut4life.ac.za': { id: 'local-admin-nomsa', name: 'Nomsa Dlamini', role: 'admin', password: 'SkillQuestDemo1!' },
} as const;

const LOCAL_DEMO_SESSION_KEY = 'skillquest.local-demo-session.v1';

function readLocalDemoEmail(): string | null {
  if (typeof window === 'undefined') return null;
  const value = window.localStorage.getItem(LOCAL_DEMO_SESSION_KEY);
  return value && value.trim().toLowerCase() in LOCAL_DEMO_USERS ? value.trim().toLowerCase() : null;
}

function toDemoUser(email: string) {
  const account = LOCAL_DEMO_USERS[email as keyof typeof LOCAL_DEMO_USERS];
  return {
    id: account.id,
    aud: 'authenticated',
    role: 'authenticated',
    email,
    email_confirmed_at: new Date(0).toISOString(),
    user_metadata: {
      name: account.name,
      demo: true,
      role: account.role,
    },
    app_metadata: { provider: 'demo', providers: ['demo'] },
    created_at: new Date(0).toISOString(),
    updated_at: new Date().toISOString(),
  };
}

function makeLocalDemoTable() {
  return {
    select: () => makeLocalDemoTable(),
    eq: () => makeLocalDemoTable(),
    order: () => makeLocalDemoTable(),
    limit: () => makeLocalDemoTable(),
    delete: async () => ({ data: null, error: null }),
    insert: async (value: unknown) => ({ data: value, error: null }),
    update: async (value: unknown) => ({ data: value, error: null }),
    upsert: async (value: unknown) => ({ data: value, error: null }),
    maybeSingle: async () => ({ data: null, error: null }),
    single: async () => ({ data: null, error: null }),
  };
}

function createLocalDemoSupabase() {
  return {
    auth: {
      signInWithPassword: async ({ email, password }: { email: string; password: string }) => {
        const normalized = email.trim().toLowerCase();
        const account = LOCAL_DEMO_USERS[normalized as keyof typeof LOCAL_DEMO_USERS];

        if (!account || account.password !== password) {
          return {
            data: { user: null, session: null },
            error: { message: 'Invalid login credentials' },
          };
        }

        if (typeof window !== 'undefined') {
          window.localStorage.setItem(LOCAL_DEMO_SESSION_KEY, normalized);
        }

        const user = toDemoUser(normalized);
        const session = {
          access_token: `demo.${btoa(normalized)}.session`,
          token_type: 'bearer',
          expires_in: 60 * 60 * 24 * 365,
          expires_at: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365,
          refresh_token: `demo-refresh-${normalized}`,
          user,
        };

        return { data: { user, session }, error: null };
      },
      getSession: async () => {
        const email = readLocalDemoEmail();
        if (!email) return { data: { session: null }, error: null };
        const user = toDemoUser(email);
        return {
          data: {
            session: {
              access_token: `demo.${btoa(email)}.session`,
              token_type: 'bearer',
              expires_in: 60 * 60 * 24 * 365,
              expires_at: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365,
              refresh_token: `demo-refresh-${email}`,
              user,
            },
          },
          error: null,
        };
      },
      getUser: async () => {
        const email = readLocalDemoEmail();
        if (!email) return { data: { user: null }, error: null };
        return { data: { user: toDemoUser(email) }, error: null };
      },
      onAuthStateChange: () => ({
        data: {
          subscription: {
            unsubscribe: () => undefined,
          },
        },
      }),
      signOut: async () => {
        if (typeof window !== 'undefined') {
          window.localStorage.removeItem(LOCAL_DEMO_SESSION_KEY);
        }
        return { error: null };
      },
      resetPasswordForEmail: async () => ({ error: null }),
    },
    from: () => makeLocalDemoTable(),
    functions: {
      invoke: async () => ({ data: null, error: null }),
    },
  };
}

const DEMO_USERS = {
  'demo.student@dut4life.ac.za': {
    id: '00000000-0000-4000-8000-000000000001',
    name: 'Demo Student',
    role: 'student',
  },
  'demo.staff@dut4life.ac.za': {
    id: '00000000-0000-4000-8000-000000000002',
    name: 'Demo Staff',
    role: 'staff',
  },
  'demo.admin@dut4life.ac.za': {
    id: '00000000-0000-4000-8000-000000000003',
    name: 'Demo Admin',
    role: 'admin',
  },
} as const;

const DEMO_SESSION_KEY = 'skillquest.demo-session.v1';

type DemoEmail = keyof typeof DEMO_USERS;
type DemoListener = (event: string, session: unknown) => void;

function isDemoEmail(email: string): email is DemoEmail {
  return email.trim().toLowerCase() in DEMO_USERS;
}

function demoUser(email: DemoEmail) {
  const account = DEMO_USERS[email];
  return {
    id: account.id,
    aud: 'authenticated',
    role: 'authenticated',
    email,
    email_confirmed_at: new Date(0).toISOString(),
    user_metadata: {
      name: account.name,
      demo: true,
      role: account.role,
    },
    app_metadata: { provider: 'demo', providers: ['demo'] },
    created_at: new Date(0).toISOString(),
    updated_at: new Date().toISOString(),
  };
}

function demoSession(email: DemoEmail) {
  return {
    access_token: `demo.${btoa(email)}.session`,
    token_type: 'bearer',
    expires_in: 60 * 60 * 24 * 365,
    expires_at: Math.floor(Date.now() / 1000) + 60 * 60 * 24 * 365,
    refresh_token: `demo-refresh-${email}`,
    user: demoUser(email),
  };
}

function createDemoAuth(realAuth: any): any {
  const listeners = new Set<DemoListener>();
  let demoEmail: DemoEmail | null = null;

  const readStoredEmail = (): DemoEmail | null => {
    if (typeof window === 'undefined') return null;
    const value = window.localStorage.getItem(DEMO_SESSION_KEY);
    return value && isDemoEmail(value) ? value : null;
  };

  const currentEmail = () => demoEmail ?? readStoredEmail();
  const currentSession = () => {
    const email = currentEmail();
    return email ? demoSession(email) : null;
  };
  const notify = (event: string, session: unknown) => {
    for (const listener of listeners) listener(event, session);
  };

  return new Proxy(realAuth, {
    get(target, property, receiver) {
      if (property === 'signInWithPassword') {
        return async ({ email }: { email: string; password: string }) => {
          const normalized = email.trim().toLowerCase();
          if (!isDemoEmail(normalized)) return Reflect.get(target, property, receiver).apply(target, arguments as never);
          demoEmail = normalized;
          if (typeof window !== 'undefined') window.localStorage.setItem(DEMO_SESSION_KEY, normalized);
          const session = demoSession(normalized);
          notify('SIGNED_IN', session);
          return { data: { user: session.user, session }, error: null };
        };
      }

      if (property === 'getSession') {
        return async () => {
          const session = currentSession();
          return session ? { data: { session }, error: null } : Reflect.get(target, property, receiver).apply(target, []);
        };
      }

      if (property === 'getUser') {
        return async () => {
          const session = currentSession();
          return session ? { data: { user: session.user }, error: null } : Reflect.get(target, property, receiver).apply(target, []);
        };
      }

      if (property === 'signOut') {
        return async () => {
          const wasDemo = Boolean(currentEmail());
          demoEmail = null;
          if (typeof window !== 'undefined') window.localStorage.removeItem(DEMO_SESSION_KEY);
          if (wasDemo) {
            notify('SIGNED_OUT', null);
            return { error: null };
          }
          return Reflect.get(target, property, receiver).apply(target, []);
        };
      }

      if (property === 'onAuthStateChange') {
        return (callback: DemoListener) => {
          listeners.add(callback);
          const realSubscription = Reflect.get(target, property, receiver).apply(target, [callback]);
          return {
            data: {
              subscription: {
                unsubscribe: () => {
                  listeners.delete(callback);
                  realSubscription?.data?.subscription?.unsubscribe?.();
                },
              },
            },
          };
        };
      }

      return Reflect.get(target, property, receiver);
    },
  });
}

function createSupabaseClient() {
  const SUPABASE_URL = import.meta.env['VITE_SUPABASE_URL'] || process.env['SUPABASE_URL'];
  const SUPABASE_PUBLISHABLE_KEY = import.meta.env['VITE_SUPABASE_PUBLISHABLE_KEY'] || process.env['SUPABASE_PUBLISHABLE_KEY'];

  if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
    return createLocalDemoSupabase() as ReturnType<typeof createSupabaseClient>;
  }

  const client = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    global: {
      fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY),
    },
    auth: {
      storage: brokeredPreviewStorage(),
      persistSession: true,
      autoRefreshToken: true,
    },
  });

  return client;
}

let _supabase: ReturnType<typeof createSupabaseClient> | undefined;
let _demoAuth: any;

export const supabase = new Proxy({} as ReturnType<typeof createSupabaseClient>, {
  get(_, prop, receiver) {
    if (!_supabase) _supabase = createSupabaseClient();
    if (prop === 'auth') _demoAuth ??= createDemoAuth(_supabase.auth);
    return prop === 'auth' ? _demoAuth : Reflect.get(_supabase, prop, receiver);
  },
});

export const demoLocalUsers = LOCAL_DEMO_USERS;
export const isDemoLocalMode = true;
